[versions]
firebase-auth = "20.0.0"
firebase-firestore = "23.0.3"
firebase-database = "20.0.3"
androidx-core = "1.7.0"
androidx-lifecycle = "2.4.0"
activityKtx = "1.8.0"
firebase = "32.0.0"  # Remplace par la dernière version de Firebase
google-services = "4.3.15"  # Dernière version du plugin google-services
lifecycle = "2.5.0"
agp = "8.9.0"
kotlin = "2.0.21"
google.services = "4.3.15"
firebaseBom = "33.11.0"
coreKtx = "1.10.1"
lifecycleRuntimeKtx = "2.6.2"
junit = "4.13.2"
androidxJunit = "1.1.5"
espressoCore = "3.5.1"
material = "1.10.0"



[libraries]

okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.9.3" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.1" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.6.0" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version = "18.0.0" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Firebase

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }


